version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20  # Required for Docker commands

  pre_build:
    commands:
      - echo "=== Preparing Build Environment ==="
      - docker info  # Verify Docker is working
      - echo "Using public Docker Hub image: sthirpr/wild-rydes-app:latest"

  build:
    commands:
      - echo "=== Generating ECS Deployment File ==="
      - echo '[{"name":"wild-rydes-app","imageUri":"sthirpr/wild-rydes-app:latest"}]' > imagedefinitions.json
      - cat imagedefinitions.json  # Verify file content

  post_build:
    commands:
      - echo "=== Build Completed Successfully ==="
      - echo "ECS will use the specified Docker Hub image"

artifacts:
  files:
    - imagedefinitions.json
  discard-paths: yes
